# Basic Config
name: Development blog of Josh Frankel
tagline: Web Development simplified

# Author
author:
    name: Josh Frankel
    github: https://github.com/joshmfrankel
    stackoverflow: http://stackoverflow.com/users/906974/josh-frankel
    twitter: https://twitter.com/Joshmfrankel
    linkedin: http://www.linkedin.com/in/joshmfrankel
    feedburner: "http://feedburner.google.com/fb/a/mailverify?uri=blogjoshmfrankel&amp;loc=en_US"

# Site Settings
url: http://joshfrankel.me/blog
paginate: 6
permalink: /:year/:categories/:title
excerpt_separator: <!--more-->

# Plugins
markdown: redcarpet
pygments: true
