# Basic Config
name: Blog of Josh Frankel
tagline: Web Development simplified
description: Explosions! Ranting! and Web Development!

# Author
author:
    name: Josh Frankel
    github: https://github.com/joshmfrankel
    stackoverflow: http://stackoverflow.com/users/906974/josh-frankel
    twitter: https://twitter.com/Joshmfrankel
    linkedin: http://www.linkedin.com/in/joshmfrankel

# Site Settings
url: blog.joshfrankel.me
paginate: 6
permalink: /:year/:categories/:title
excerpt_separator: <!--more-->

# Plugins
markdown: redcarpet
pygments: true
