# Basic Config
name: Development blog of Josh Frankel
tagline: Web Development simplified

# Author
author:
    name: Josh Frankel
    github: https://github.com/joshmfrankel
    stackoverflow: http://stackoverflow.com/users/906974/josh-frankel
    twitter: https://twitter.com/Joshmfrankel
    linkedin: http://www.linkedin.com/in/joshmfrankel
    google: https://plus.google.com/+JoshFrankelWebDeveloper
    feedburner: "http://feedburner.google.com/fb/a/mailverify?uri=blogjoshmfrankel&amp;loc=en_US"

# Site Settings
url: http://joshfrankel.me/blog
imgurl: http://joshfrankel.me/
paginate: 6
paginate_path: "/page/:num/"
permalink: /:year/:categories/:title
excerpt_separator: <!--more-->

# Development setup
dev:
    url: http://localhost:4000

env: development

# Plugins
markdown: redcarpet
highlighter: pygments
